service: s3-event-driven-function
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: python3.9
  region: ap-northeast-1
  stage: ${opt:stage, self:custom.default-stage}

custom:
  default-stage: dev

functions:
  event-driven-function:
    handler: src/handler.execute
