name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 17
          cache: npm
      - name: Install npm packages
        run: |
          npm install
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install python packages via pipenv
        run: |
          pip install pipenv
          pipenv sync --dev
      - name: check and lint
        run: |
          pipenv run check
          pipenv run lint
          pipenv run type

      - name: Which sls
        run: |
          npx serverless -h
        working-directory: s3_event_driven_function
