name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 17
          cache: npm
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: install boto3
        run: |
          pip install boto3
      - name: sls invoke locally
        run: |
          npm install -g serverless
          sls invoke local -f event-handler-function -p test/event.json
