name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 17
          cache: npm
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: install requirements
        run: |
          pip install -r requirements.txt
      - name: install serverless
        run: |
          npm install -g serverless
      - name: sls invoke locally
        run: |
          sls invoke local -f event-driven-function -p tests/event.json
        working-directory: s3-event-driven-function
